### ISSUE TITLE
Respect removed previews

### ISSUE THREAD

**Issue by rkuska** [kiwicom/gitlab-unfurly#10]
I create a post containing many gitlab links and unfurly automatically unfurls them. Yet when I click on `x` at every relevant link unfurly will again generate the views. I would expect unfurly to respect removed previews.

I understand that unfurly is probably stateless but then I would expect to have an (easy) option to not unfurl any link in the post.

**Comment by underyx** [comment]
Yep, just add `?no_unfurl` to the URL and it will be skipped.

**Comment by martin-sucha** [comment]
Couldn't clicking the `x` add it automatically?

**Comment by underyx** [comment]
And the behavior you describe sounds like a bug on Slack's end, no? Why does Slack ask unfurly for link details again? Please report it to them.

**Comment by rkuska** [comment]
1. Can this to be adjusted for the whole post? It's tiresome to add it to every url. 
2. Can this be documented?

**Comment by underyx** [comment]
@martin-sucha we have rights only to read URLs, so no.

**Comment by underyx** [comment]
@rkuska as for 1, Slack gives us the individual URLs, not even the whole message, so no. As for 2, pull requests welcome 😌

**Comment by rkuska** [comment]
As for 2, done.
