### ISSUE TITLE
Remove docker requirement

### ISSUE THREAD

**Issue by carlin-q-scott** [kiwicom/gitlab-unfurly#15]
I tried deploying this but it requires docker for some reason. Is that a necessary requirement?

**Comment by aexvir** [comment]
Hi Carlin,
Docker is needed for `dockerizePip`, which allows building wheels cross-systems and ensures compatibility with the lambda runtime. With that said... I don't see why any of our requirements would need it, so I'm pretty sure we can remove it safely 🙂

**Comment by carlin-q-scott** [comment]
Excellent. I set it to false so that Windows users can re-enable it.
