### ISSUE TITLE
Ignore comments when unfurlying 

### ISSUE THREAD

**Issue by rkuska** [kiwicom/gitlab-unfurly#3]
GitLab Flavored Markdown (GFM) supports [two styles](https://about.gitlab.com/handbook/product/technical-writing/markdown-guide/#comments) of comments (for some reason `{::comment}` doesn't work for me in issues). We use html comments in our templates to let user know what we expect him to fill but when the issue/MR is unfurled it contains these comments in the preview.

Example of unpleasant look of unfurled issue which contains html comments:

<img width="589" alt="screenshot 2019-01-03 at 10 07 59" src="https://user-images.githubusercontent.com/1709417/50630415-13251900-0f41-11e9-99b0-6a2a6d3eb85b.png">

**Comment by JanBednarik** [comment]
We can remove HTML tags (including HTML comments) using [Bleach](https://github.com/mozilla/bleach) and leave just plaintext content.

**Comment by underyx** [comment]
That's a pretty good solution, nice! Thanks @JanBednarik 🙃

**Comment by rkuska** [comment]
Thank you for fixing this! World looks slightly nicer now.
