### ISSUE TITLE
Add a bit more to the docs

### ISSUE THREAD

**Issue by alexeyzimarev** [kiwicom/gitlab-unfurly#9]
It would be nice to get an idea what to do in Slack in order to make the app working.

**Comment by rkuska** [comment]
Together with some short description about how unfurly works to understand its limitations.

**Comment by aexvir** [comment]
Done in https://github.com/kiwicom/gitlab-unfurly/pull/16/commits/3673648f540f810d16204152df9a7e155c3ec912
